version: '3.8'
name: logic

services:
  web:
    container_name: logic
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/var/www  
    user: root 